export default [
	{ id: '1', imageName: 'image1.jpg', tag: 'Ui/Ux Design' },
	{ id: '2', imageName: 'image2.jpg', tag: 'graphic design' },
	{ id: '3', imageName: 'image3.jpg', tag: 'graphic design' },
	{ id: '4', imageName: 'image10.jpg', tag: 'graphic design' },
	{ id: '5', imageName: 'image5.jpg', tag: 'graphic design' },
	{ id: '6', imageName: 'image6.jpg', tag: 'graphic design' },
	{ id: '7', imageName: 'image7.jpg', tag: 'Ui/Ux Design' },
	{ id: '8', imageName: 'image8.jpg', tag: 'graphic design' },
	{ id: '9', imageName: 'image9.png', tag: 'Ui/Ux Design' },
	{ id: '10', imageName: 'image11.jpg', tag: 'Ui/Ux Design' },
	{ id: '11', imageName: 'image12.jpg', tag: 'Ui/Ux Design' },
	{ id: '12', imageName: 'image13.jpg', tag: 'Ui/Ux Design' },
	{ id: '13', imageName: 'image14.jpg', tag: 'graphic design' },
	{ id: '14', imageName: 'image15.jpg', tag: 'graphic design' },
];